### ISSUE TITLE
[Bug Report] Illegal Memory Access when using `flash_attn_varlen_qkvpacked_func`

### ISSUE THREAD

**Issue by xTayEx** [Dao-AILab/flash-attention#1042]
# 🐛 Bug Description
I am encountering the "illegal memory access" error when using `flash_attn_varlen_qkvpacked_func` on H800. The minimal code to reproduce the error is shown below:
```python
import argparse
import torch
from flash_attn import flash_attn_varlen_qkvpacked_func

torch.set_printoptions(sci_mode=False, precision=8)

parser = argparse.ArgumentParser()
parser.add_argument("--seqlen", type=int, required=True)
parser.add_argument("--batch_size", type=int, required=True)
parser.add_argument("--sliding_window_size", type=int, required=True)
parser.add_argument("--repeat", type=int, default=30)
args = parser.parse_args()

dim = 4096
nheads = 32
headdim = dim // nheads
num_kv_heads = nheads

for iter in range(args.repeat):
    torch.manual_seed(123 + iter)

    cu_seqlens_content = [0]
    for _ in range(args.batch_size):
        cur_len = args.seqlen
        cu_seqlens_content.append(cu_seqlens_content[-1] + cur_len)

    cu_seqlens = torch.tensor(cu_seqlens_content, device="cuda:0", dtype=torch.int32)
    total = cu_seqlens_content[-1]
    assert total == args.seqlen * args.batch_size

    qkv = torch.normal(
        mean=0.0,
        std=0.005,
        device="cuda:0",
        dtype=torch.float16,
        size=(total, 3, nheads, headdim),
    ).contiguous()

    flash_attn_result = flash_attn_varlen_qkvpacked_func(
        qkv, cu_seqlens, max_seqlen=args.seqlen, causal=True, window_size=(args.sliding_window_size, 0)
    )
    torch.cuda.synchronize()
```
Run the above script using the following command should cause the error:
```bash
 CUDA_LAUNCH_BLOCKING=1 python3 run_flashattn.py --seqlen 512 --batch_size 710 --sliding_window_size 63 --repeat 50
```
```bash
Traceback (most recent call last):
  File "/xxx/run_flashattn.py", line 39, in <module>
    flash_attn_result = flash_attn_varlen_qkvpacked_func(
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/flash_attn_interface.py", line 887, in flash_attn_varlen_qkvpacked_func
    return FlashAttnVarlenQKVPackedFunc.apply(
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 571, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/flash_attn_interface.py", line 288, in forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = _flash_attn_varlen_forward(
  File "/usr/local/lib/python3.10/dist-packages/flash_attn/flash_attn_interface.py", line 85, in _flash_attn_varlen_forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.varlen_fwd(
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions
```
# Environment
## GPU Information
```txt
Thu Jul 11 04:36:58 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.5     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA H800                    On  | 00000000:23:00.0 Off |                    0 |
| N/A   28C    P0              69W / 700W |      7MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA H800                    On  | 00000000:33:00.0 Off |                    0 |
| N/A   27C    P0              68W / 700W |      7MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA H800                    On  | 00000000:43:00.0 Off |                    0 |
| N/A   28C    P0              68W / 700W |      7MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA H800                    On  | 00000000:63:00.0 Off |                    0 |
| N/A   27C    P0              66W / 700W |      7MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   4  NVIDIA H800                    On  | 00000000:83:00.0 Off |                    0 |
| N/A   27C    P0              69W / 700W |      7MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   5  NVIDIA H800                    On  | 00000000:A3:00.0 Off |                    0 |
| N/A   28C    P0              68W / 700W |      7MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   6  NVIDIA H800                    On  | 00000000:C3:00.0 Off |                    0 |
| N/A   38C    P0              71W / 700W |      7MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   7  NVIDIA H800                    On  | 00000000:E3:00.0 Off |                    0 |
| N/A   28C    P0              69W / 700W |      7MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

## Package Information
```txt
python version: 3.10.12
cuda version: 12.5.40
flash-attn version: 2.4.2
pytorch version: 2.4.0a0+f70bd71a48.nv24.6
```

# Request for Help
I would appreciate any guidance on how to resolve this illegal memory access issue. Thank you!

**Comment by YXD942** [comment]
same!

**Comment by YXD942** [comment]
@xTayEx Sorry, have you solved this problem?

**Comment by xTayEx** [comment]
> [@xTayEx](https://github.com/xTayEx) Sorry, have you solved this problem?

Hi! When I encountered this issue, it turned out to be a mistake in my arguments. Since it was so long ago, I can't recall the exact details. If your case is similar, I recommend checking your usage first. If the problem persists, opening a new issue would help the community assist you better! 😄
