### ISSUE TITLE
illegal memory access / invalid program counter when uncommenting one tensor print in bwd

### ISSUE THREAD

**Issue by ds-kczerski** [Dao-AILab/flash-attention#1657]
Hello,

in **flash_bwd_kernel.h**
when I uncomment line 465 in the latest main, namely a tensor printing (you can also ctrl+F this)
```
if (cute::thread0()) { print(sK); }
```
I'm getting an illegal memory access or invalid program counter error, depending on the problem size I run. However, for all problem sizes I've tried so far (hdim 32), I encounter this error.

What does this mean?

Can it reveal bugs or undefined behavior that expose memory-related issues? For example, when adding a printf line causes the code to compile differently?

I don't encounter any issues when printing tensors in earlier lines in the backward pass, and I have no problems printing tensors at all in the forward pass.

For additional context, this line is just after
```
cute::cp_async_wait<0>();
__syncthreads();
```

**Comment by ds-kczerski** [comment]
This is the instruction to recreate the issue

1. uncomment the below line in `flash_bwd_kernel.h`. Ctrl+f to find:
```cpp
if (cute::thread0()) { print(sK); }
```
2. call this minimalistic code
```python
import torch
from flash_attn import flash_attn_func

# Example parameters
batch_size = 2
seqlen = 64
nheads_q = 16
nheads_kv = 16
headdim = 16

device = torch.device("cuda")

q = torch.randn(batch_size, seqlen, nheads_q, headdim, device=device, dtype=torch.float16, requires_grad=True)
k = torch.randn(batch_size, seqlen, nheads_kv, headdim, device=device, dtype=torch.float16, requires_grad=True)
v = torch.randn(batch_size, seqlen, nheads_kv, headdim, device=device, dtype=torch.float16, requires_grad=True)


out = flash_attn_func(q, k, v, dropout_p=0.0, causal=False)

# Ensure all CUDA operations are done before printing
torch.cuda.synchronize()

# Move to CPU and convert to float32 for clearer printing (this works fine)
# print(out.detach().cpu().float())

loss = out.sum()
loss.backward()

torch.cuda.synchronize()  # probably not necessary

q_grad = q.grad.clone()

print(q_grad.detach().cpu().float())
 ```

I am running on A100 80GB, and I am building with nvcc 12.4 and also 12.9

**Comment by ds-kczerski** [comment]
I'm adding more print statements to the code (just printing the shape of the Sk tensor), and suddenly something goes wrong. I'm using the vanilla backward code and only adding prints. Could you please help me understand what might be causing this? I’ve been doing some custom modifications and encountered undefined behavior in other parts, but this is a minimal example where I can reproduce the issue, starting from the unmodified code.

```cpp
    if (cute::thread(0, 0) && n_block == 0) { printf("sK layout (5): "); print(sK.layout()); printf("\n"); }

    for (; m_block >= m_block_min; --m_block) {
      if (cute::thread(0, 0) && n_block == 0) { printf("sK layout (6): "); print(sK.layout()); printf("\n"); }
        Tensor acc_s = partition_fragment_C(tiled_mma_sdp, Shape<Int<kBlockM>, Int<kBlockN>>{});  // (MMA=4, MMA_N, MMA_N)
        clear(acc_s);
        if (cute::thread(0, 0) && n_block == 0) { printf("sK layout (7): "); print(sK.layout()); printf("\n"); }
        cute::cp_async_wait<0>();
        __syncthreads();

        if (cute::thread(0, 0) && n_block == 0) { printf("sK layout (8): "); print(sK.layout()); printf("\n"); }
    // ... 
```
this ends up with

```bash
sK layout: Sw<2,3,3> o _0 o (_128,_32):(_32,_1)
sK layout (2): Sw<2,3,3> o _0 o (_128,_32):(_32,_1)
sK layout (3): Sw<2,3,3> o _0 o (_128,_32):(_32,_1)
sK layout (4): Sw<2,3,3> o _0 o (_128,_32):(_32,_1)
sK layout (5): Sw<2,3,3> o _0 o (_128,_32):(_32,_1)
sK layout (6): Sw<1103101960,3,3>Traceback (most recent call last):
````

This is very strange to me. I can't run ncu on this machine (no privileges), but in the past, when I was able to run it, these lines were roughly where registers ran out and register spilling started to occur. Please also note that everything is from the original DAO code - I’ve only added these print statements. In the post above, I’ve encapsulated it as a minimal example to reproduce the issue.

@tridao Could you please help me and take a look at this sK tensor?@tridao  Could you please help me and take a look on this `sK` tensor?

**Comment by tridao** [comment]
Are you using FA2 or FA3 code?
FA2 uses this unsafe `convert_type`:
https://github.com/Dao-AILab/flash-attention/blob/e9e96d3d1ab66a6f815d77ef11398f637de3e4f4/csrc/flash_attn/src/utils.h#L229
This is only ok if the compiler actually inlines the function (we do specify `__forceinline__`). However sometimes when there are print statements the compiler does not inline the function and all hell breaks loose.

FA3 uses this safe `convert_type_out` which requires the caller to allocate the output first.
https://github.com/Dao-AILab/flash-attention/blob/e9e96d3d1ab66a6f815d77ef11398f637de3e4f4/hopper/utils.h#L211


FA3 code should work with A100 now

**Comment by ds-kczerski** [comment]
Thanks for the quick response! We're currently using FA2. Porting to FA3 — good to know it works — I'll definitely consider it, though it might take some time.

Your hint sounds very helpful! It's possible that our debug modifications (copying to global mem manually, like the prints) are causing the compiler to skip inlining the function. Fortunately, the final results in our production code seem to be working well.

I'll post an update here once I have more insight. Thanks again!

**Comment by tridao** [comment]
For FA2 you can also just replace all instances of `convert_type` with `convert_type_out` like this:
```
            Tensor rP = make_tensor_like<Element>(tSrS);
            flash::convert_type_out(tSrS, rP);
```
(and you'd need to add `conver_type_out` to `utils.h` in FA2.

**Comment by ds-kczerski** [comment]
I’ve checked this in more detail and updated all uses of `convert_type` to `convert_type_out` in bwd code (and similarly replaced `convert_type_relu` with `convert_type_relu_out`, which is only relevant when `dropout != 0`). However, this change did **not** resolve the issue.

Next, I inspected the generated PTX:
- The code that runs **fine** (vanilla, no prints) has **no non-inlined functions**.
- The code that is **faulty** (vanilla + print added) has **one non-inlined function**, and it is the printing function itself:
```
.extern .func  (.param .b32 func_retval0) vprintf
(
	.param .b64 vprintf_param_0,
	.param .b64 vprintf_param_1
)
;
// ...

call.uni (retval0), 
```
So the non-inlining of the `convert_type` functions is not the cause.

I also ran `compute-sanitizer --tool memcheck`:
- The working (vanilla, no print) version reports **0 errors**.
- The faulty (with print) version reports **3 errors**.

To sum up:
- The vanilla FlashAttention 2 backward pass runs fine.
- Modifications (e.g., adding `printf`) may cause undefined behavior.
- In practice, we see these issues only in debug builds, so we will continue working with FA2 and try to keep the production path safe and stable.

I’ll also post updates here if we discover more about this undefined behavior, or in case we decide to switch to FA3 (we still need to evaluate how easy it would be to port).

@tridao If you have any further suggestions for debugging or tracking these issues, I’d really appreciate it.
