### ISSUE TITLE
device kernel image is invalid, flash_attn==2.8.1

### ISSUE THREAD

**Issue by GitMonkey0** [Dao-AILab/flash-attention#1749]
flash_attn/flash_attn_interface.py", line 165, in _flash_attn_varlen_forward
[rank0]:     out, softmax_lse, S_dmask, rng_state = flash_attn_gpu.varlen_fwd(
[rank0]: RuntimeError: CUDA error: device kernel image is invalid
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by GitMonkey0** [comment]
2.8.0 works for me, maybe a problem of new release?

**Comment by trmusson** [comment]
Just a note to confirm that I was getting the same error as GitMonkey0, and reverting to an older version solved it. (Specifically, I replaced 2.8.1 with 2.8.0.post2 via pip.)

**Comment by GitMonkey0** [comment]
> Just a note to confirm that I was getting the same error as GitMonkey0, and reverting to an older version solved it. (Specifically, I replaced 2.8.1 with 2.8.0.post2 via pip.)

yep, I fixed this issue in version 2.8.0.post2 too. But now, most mainstream projects default to installing the latest version 2.8.1. That means every time I start the container, I have to go through the tedious process of reinstalling with  pip install flash_attn==2.8.0.post2 . I'm curious—does this problem happen across all GPU types and CUDA versions?

**Comment by trmusson** [comment]
> I'm curious—does this problem happen across all GPU types and CUDA versions?

Here I'm using an RTX 3060 (according to nvidia-smi: Driver Version: 535.247.01, CUDA Version: 12.2) on Ubuntu 22.04.5 LTS.

**Comment by JamesSand** [comment]
>  I'm curious—does this problem happen across all GPU types and CUDA versions?

Same problem when using A100 (Driver Version: 545.23.08    CUDA Version: 12.3 ), with Ubuntu 22.04.3 LTS

**Comment by JamesSand** [comment]
Another question. Does 2.8.0.post2 support torch 2.8.0? I don't find any release for torch 2.8.0 on flash-attention 2.8.0.post2.
