### ISSUE TITLE
[Blackwell/RTX 5090] CUDA kernel crash on FlashAttention with Voxtral-Mini-3B-2507

### ISSUE THREAD

**Issue by Jacketbg** [Dao-AILab/flash-attention#1763]
## Summary

Trying to run the Voxtral-Mini-3B-2507 model via vLLM on a new NVIDIA RTX 5090 (Blackwell) GPU results in a CUDA error when initializing FlashAttention:

CUDA error (/__w/xformers/xformers/third_party/flash-attention/hopper/flash_fwd_launch_template.h:188): invalid argument
...
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}

## Environment

- GPU: NVIDIA RTX 5090 (Blackwell, sm_120)
- Host: Debian 12
- Driver: 570.169
- CUDA: 12.8
- PyTorch: Nightly (latest, installed with `--pre` and cu128)
- vLLM: Nightly (`pip install -U "vllm[audio]" --extra-index-url https://wheels.vllm.ai/nightly`)
- FlashAttention: <your installed version, or tried latest nightlies>
- Ray[serve]: latest

## Steps to Reproduce

1. Set up a virtual environment
2. Install all dependencies as above
3. Run:
   vllm serve mistralai/Voxtral-Mini-3B-2507 --tokenizer_mode mistral --config_format mistral --load_format mistral
4. Observe CUDA kernel error in FlashAttention code

## Notes

- Issue persists with the latest nightly versions of all packages as of 17.07.2025.
- This appears to be missing kernel support for the Blackwell/SM120 architecture in FlashAttention or vLLM.

## Request

- Please confirm Blackwell (sm_120/RTX 5090) support status and, if not yet supported consider adding it or provide a workaround.

**Comment by 6Morpheus6** [comment]
@Jacketbg I had this problem too. It seems to come from xformers.
If you are using torch 2.7.1 and the according xformers version xformers 0.0.31.post1 try to downgrade torch and xformers.
Activate your app environment and use this command:
`pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 xformers==0.0.30 --index-url https://download.pytorch.org/whl/cu128 --force-reinstall --no-deps`
Or if uv is installed, use this one:
`uv pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 xformers==0.0.30 --index-url https://download.pytorch.org/whl/cu128 --force-reinstall --no-deps`

**Comment by koiker** [comment]
I have an RTX PRO 6000 with 96GB RAM and I do have the OOM errors.
Tried all the examples above and no one worked.

**Comment by jians5** [comment]
I'm having this problem but it doesn't say "CUDA" but instead:

`UDA error (C:/a/xformers/xformers/third_party/flash-attention/hopper\flash_fwd_launch_template.h:188): invalid argument`

C:/a does not exist on my system.

I did install kohya yesterday so that's probably what broke it, but I tried the reinstall solution above but it did not help.

**Comment by koiker** [comment]
I was able to solve the issue by building xformers from source, from a commit that includes the Blackwell cuda.
The command is:
`pip install --no-build-isolation --pre -v -U git+https://github.com/facebookresearch/xformers.git@fde5a2fb46e3f83d73e2974a4d12caf526a4203e`

**Comment by prijkes** [comment]
It really needs to be the version that @koiker  specified. The latest xformers doesn't work either.

**Comment by AmmarkoV** [comment]
> I was able to solve the issue by building xformers from source, from a commit that includes the Blackwell cude. The command is: `pip install --no-build-isolation --pre -v -U git+https://github.com/facebookresearch/xformers.git@fde5a2fb46e3f83d73e2974a4d12caf526a4203e`

THANK YOU!

**Comment by BobMind758** [comment]
pytorch2.7.1安装的是xformers0.0.3.1，降回pytorch2.7.0安装xformers0.0.3.0就好了

**Comment by house-tour** [comment]
> I was able to solve the issue by building xformers from source, from a commit that includes the Blackwell cude. The command is: `pip install --no-build-isolation --pre -v -U git+https://github.com/facebookresearch/xformers.git@fde5a2fb46e3f83d73e2974a4d12caf526a4203e`

Works for me on torch2.8.0+cu128, python3.10 as well!

**Comment by rayryeng** [comment]
Leaving this comment because I also had the same issue. None of the above commands worked in this thread. I'm using Torch 2.9.0, CUDA 12.8 and on an RTX PRO 6000. What worked for me was to build the latest version of the source. I additionally had to specify 12.0 due to the RTX PRO 6000 being part of the Blackwell architecture in the `TORCH_CUDA_ARCH_LIST` environment variable before building it.

As [per the instructions on the xformers repo](https://github.com/facebookresearch/xformers?tab=readme-ov-file#installing-xformers):

```bash
pip install ninja
export TORCH_CUDA_ARCH_LIST="12.0"
pip install -v --no-build-isolation -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
```

This may take a while, but once it finally installed, that error finally went away.

**Comment by Jacketbg** [comment]
Was excited to try this. However, it seems to fail with this error:

```ValueError: Unknown CUDA arch (12.0) or GPU not supported```

Any idea what might be going wrong? RTX 5090 with Cuda 12.8.

**Comment by rayryeng** [comment]
> Was excited to try this. However, it seems to fail with this error:
> 
> ```ValueError: Unknown CUDA arch (12.0) or GPU not supported```
> 
> Any idea what might be going wrong? RTX 5090 with Cuda 12.8.

Check your CUDA device capability and set the string accordingly. RTX 5090 should be Blackwell, hence setting it to 12.0

```python
import torch
print(torch.cuda.get_device_capability())
```

This will return a tuple of 2 numbers. The first number is the major number and the second the minor number. You separate them by a period. Whatever those two numbers are, set the `TORCH_CUDA_ARCH_LIST` accordingly. Mine returns 12 and 0 respectively, so I set it to 12.0.

I also forgot to mention that you need to have the CUDA toolkit installed. I assume you do, given the context of this discussion. 

One last thing is to make sure you have a compatible version of PyTorch that supports the Blackwell architecture. Since 2.7.1, you no longer need to use nightly builds and Blackwell was officially supported in the stable versions since this release. Make sure you have at least this version and up. I used 2.9.0 as it is the most stable version currently.

**Comment by Jacketbg** [comment]
My bad, pytorch was the wrong version for this project
```
pip uninstall -y torch torchvision torchaudio
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
```
And then
```
pip install ninja
export TORCH_CUDA_ARCH_LIST="12.0"
pip install -v --no-build-isolation -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
```
It's all good now. Thanks for the tip!

**Comment by rayryeng** [comment]
> My bad, pytorch was the wrong version for this project
> ```
> pip uninstall -y torch torchvision torchaudio
> pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
> ```
> And then
> ```
> pip install ninja
> export TORCH_CUDA_ARCH_LIST="12.0"
> pip install -v --no-build-isolation -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
> ```
> It's all good now. Thanks for the tip!

Any time! Glad to have helped 😊

**Comment by edobobo** [comment]
Hello I don't know whether this can be still  useful for you or not but, with the new version of `xformers` and `torch 2.9.0` it should work just fine.

```bash
pip install torch==2.9.0
pip install xformers==0.0.33.post1
```

**Comment by peter941221** [comment]
I have an RTX 5090 locally and started looking at this path because the crash site is interesting: it is in xformers vendored flash-attention hopper code, not just a generic vLLM failure.

I am working on this and will propose plan soon.

**Comment by rayryeng** [comment]
> I have an RTX 5090 locally and started looking at this path because the crash site is interesting: it is in xformers vendored flash-attention hopper code, not just a generic vLLM failure.\n\nMy read so far is that there are at least two different Blackwell failure modes floating around this stack: no kernel image is available on some prebuilt xformers or flash-attn combinations, and invalid argument in the hopper launch path like this issue.\n\nI can help narrow whether this one is mainly missing Blackwell kernel coverage, a bad launch or config path on sm_120, or a backend selection issue in the vLLM or xformers integration.\n\nWould a useful first step be a minimal standalone repro on 5090 outside the Voxtral or vLLM stack, or would you prefer this to be redirected to xformers or vLLM first?

Bruh, direct copy paste from an LLM output. Not useful.

**Comment by peter941221** [comment]
@rayryeng It only depends whether I can solve the issue or not, no matter what tools I use, right?

**Comment by rayryeng** [comment]
> @rayryeng It only depends whether I can solve the issue or not, no matter what tools I use, right?

But your "answer" didn't solve anything. Your LLM output conjectured that it was one of two possibilities and was waiting for you to choose. It is absolutely not helpful. It would have been if you actually provided an answer but there is none in this reply.

**Comment by peter941221** [comment]
@rayryeng I am just working on this, bro. Give me some time.

**Comment by rayryeng** [comment]
> @rayryeng I am just working on this, bro. Give me some time.

Maybe delete your answer until you actually find something. I'll happily delete my messages if you remove yours.

**Comment by peter941221** [comment]
@rayryeng no worry, I will propose plan soon.

**Comment by rayryeng** [comment]
> @rayryeng no worry, I will propose plan soon. 

There's no need. There have been multiple answers proposed which all work. It's fine. I'll unfollow this thread.

**Comment by peter941221** [comment]
I ran this locally on an RTX 5090 in a Linux CUDA container to separate the historical Blackwell wheel problem from any current flash-attention bug.

With torch 2.7.0+cu128 and xformers 0.0.30, the minimal xformers repro below fails immediately on the same GPU with:
CUDA error (/__w/xformers/xformers/third_party/flash-attention/hopper/flash_fwd_launch_template.h:175): no kernel image is available for execution on the device

The repro is just:
from xformers.ops import memory_efficient_attention
q, k, v = torch.randn(5, 10, 128).half().cuda(), torch.randn(5, 10, 128).half().cuda(), torch.randn(5, 10, 128).half().cuda()
memory_efficient_attention(q, k, v)

With torch 2.9.0+cu128 and xformers 0.0.33.post1, that same minimal repro succeeds on the same RTX 5090.

I also checked current flash-attention main locally: the top-level setup.py now emits sm_120 gencodes, and the tree contains explicit sm120 paths under flash_attn/cute. So at this point #1763 looks much more like a historical xformers Blackwell coverage or packaging issue than a current flash-attention mainline bug.

If someone can still reproduce the original invalid argument today, I think the most useful next step is to state the exact torch/xformers/vLLM versions and check whether the failure only remains in the integration layer. If the direct xformers repro passes on a current stack but vLLM still fails, then the next owner is probably backend selection or integration, not flash-attention core.
