### ISSUE TITLE
branch jshah/sm100-varlen-bwd  RuntimeError('NCCL Error 1: unhandled cuda error (run with NCCL_DEBUG=INFO for details)')

### ISSUE THREAD

**Issue by jamesben6688** [Dao-AILab/flash-attention#2197]
I used the branch jshah/sm100-varlen-bwd on B200 

```
from flash_attn import flash_attn_varlen_func, flash_attn_func

attn_output = flash_attn_func(
               query_states.to(torch.bfloat16), 
               key_states.to(torch.bfloat16), 
               value_states.to(torch.bfloat16),
               dropout_p=self.dropout if self.training else 0.0,
              causal=False  
            ).to(DTYPE)
```

and got the following error:

[rank0]:[E120 09:35:02.490200377 ProcessGroupNCCL.cpp:632] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLTOALL_BASE, NumelIn=25715667, NumelOut=25838968, Timeout(ms)=3600000) ran for 3600017 milliseconds before timing out.
[rank0]:[E120 09:35:02.490352569 ProcessGroupNCCL.cpp:2268] [PG ID 1 PG GUID 1 Rank 0]  failure detected by watchdog at work sequence id: 3 PG status: last enqueued work: 3, last completed work: 2
[rank0]:[E120 09:35:02.490876473 ProcessGroupNCCL.cpp:667] Stack trace of the failed collective: 

[rank0]:[E120 11:36:03.384018272 ProcessGroupNCCL.cpp:684] [Rank 0] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank0]:[E120 11:36:03.384042015 ProcessGroupNCCL.cpp:698] [Rank 0] To avoid data inconsistency, we are taking the entire process down.
[rank0]:[E120 11:36:03.385076342 ProcessGroupNCCL.cpp:1896] [PG ID 1 PG GUID 1 Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLTOALL_BASE, NumelIn=25715667, NumelOut=25838968, Timeout(ms)=3600000) ran for 3600017 milliseconds before timing out.
Exception raised from checkTimeout at 

frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xeb (0x7f64f7cb9f4b in /usr/local/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x20f (0x7f65402cf70f in /usr/local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0xc3a (0x7f65402df1ca in /usr/local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x148 (0x7f65402d33c8 in /usr/local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd44a3 (0x7f6547b3b4a3 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x891f5 (0x7f6547d0c1f5 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x1098dc (0x7f6547d8c8dc in /usr/lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 1 PG GUID 1 Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLTOALL_BASE, NumelIn=25715667, NumelOut=25838968, Timeout(ms)=3600000) ran for 3600017 milliseconds before timing out.
Exception raised from checkTimeout at 

frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xeb (0x7f64f7cb9f4b in /usr/local/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x20f (0x7f65402cf70f in /usr/local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0xc3a (0x7f65402df1ca in /usr/local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x148 (0x7f65402d33c8 in /usr/local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd44a3 (0x7f6547b3b4a3 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x891f5 (0x7f6547d0c1f5 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x1098dc (0x7f6547d8c8dc in /usr/lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at 
torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1902 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xeb (0x7f64f7cb9f4b in /usr/local/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x418 (0x7f65402d3698 in /usr/local/lib/python3.11/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xd44a3 (0x7f6547b3b4a3 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #3: <unknown function> + 0x891f5 (0x7f6547d0c1f5 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #4: <unknown function> + 0x1098dc (0x7f6547d8c8dc in /usr/lib/x86_64-linux-gnu/libc.so.6)

*** Aborted at 1768908963 (unix time) try "date -d @1768908963" if you are using GNU date ***
pixel values dtype: torch.bfloat16, pixel_values shape: torch.Size([200, 8, 3, 384, 384])
batch size: 200
PC: @     0x7f6547d0deec (unknown)
*** SIGABRT (@0x1456) received by PID 5206 (TID 0x7f56f5dff6c0) from PID 5206; stack trace: ***
    @     0x7f6547cbf050 (unknown)
    @     0x7f6547d0deec (unknown)
    @     0x7f6547cbefb2 gsignal
    @     0x7f6547ca9472 abort
    @     0x7f6547b04919 (unknown)
    @     0x7f6547b0fe1a (unknown)
    @     0x7f6547b0fe85 std::terminate()
    @     0x7f6547b0fe0e std::rethrow_exception()
    @     0x7f65402d375c c10d::ProcessGroupNCCL::ncclCommWatchdog()
    @     0x7f6547b3b4a3 (unknown)
    @     0x7f6547d0c1f5 (unknown)
    @     0x7f6547d8c8dc (unknown)
/usr/local/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 4 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
E0120 11:36:09.785000 3010 site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: -6) local_rank: 0 (pid: 5206) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

When I replace the code with:

```
attn_output = torch.nn.functional.scaled_dot_product_attention(
                query_states, key_states, value_states,
                dropout_p=self.dropout if self.training else 0.0,
                is_causal=False 
            )
```
and everything works fine.

**Comment by jayhshah** [comment]
That was merged (https://github.com/Dao-AILab/flash-attention/pull/2150), I should have deleted the branch.

**Comment by jayhshah** [comment]
Also it looks like you're using FA2 interface, that PR was about flash attention cute dsl. We don't support dropout yet: https://github.com/Dao-AILab/flash-attention/blob/04e6ee1fb54f756e6f788e6b3962a7503c985394/flash_attn/cute/interface.py#L1442

**Comment by jamesben6688** [comment]
Thank you for the quick response. I tried the main branch on B200, torch 2.7.0_cu12.8 version, but still got the error:

[rank0]:[E121 14:06:12.983246263 ProcessGroupNCCL.cpp:632] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLTOALL_BASE, NumelIn=15335125, NumelOut=15536735, Timeout(ms)=3600000) ran for 3600066 milliseconds before timing out.
[rank0]:[E121 14:06:12.983415396 ProcessGroupNCCL.cpp:2268] [PG ID 1 PG GUID 1 Rank 0]  failure detected by watchdog at work sequence id: 3 PG status: last enqueued work: 3, last completed work: 2
[rank0]:[E121 14:06:12.983964290 ProcessGroupNCCL.cpp:667] Stack trace of the failed collective: 

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 1 PG GUID 1 Rank 0] Process group watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3, OpType=ALLTOALL_BASE, NumelIn=15335125, NumelOut=15536735, Timeout(ms)=3600000) ran for 3600066 milliseconds before timing out.

PC: @     0x7f7dc8589eec (unknown)
*** SIGABRT (@0x1453) received by PID 5203 (TID 0x7f6f74fff6c0) from PID 5203; stack trace: ***
    @     0x7f7dc853b050 (unknown)
    @     0x7f7dc8589eec (unknown)
    @     0x7f7dc853afb2 gsignal
    @     0x7f7dc8525472 abort
    @     0x7f7dc8380919 (unknown)
    @     0x7f7dc838be1a (unknown)
    @     0x7f7dc838be85 std::terminate()
    @     0x7f7dc838be0e std::rethrow_exception()
    @     0x7f7dc0aea75c c10d::ProcessGroupNCCL::ncclCommWatchdog()
    @     0x7f7dc83b74a3 (unknown)
    @     0x7f7dc85881f5 (unknown)
    @     0x7f7dc86088dc (unknown)

This is how I used it: FSDP on 8 B200, used torch.compile, torch.utils.checkpoint for each transformer layer, just replaced `torch.nn.functional.scaled_dot_product_attention` with `flash_attn_func`

```
from flash_attn import flash_attn_func

attn_output = flash_attn_func(
                query_states.to(torch.bfloat16), 
                key_states.to(torch.bfloat16), 
                value_states.to(torch.bfloat16),
                causal=False  
            ).to(DTYPE)
```

**Comment by jamesben6688** [comment]
@jayhshah It seems this error has been fixed in the latest master commit. However, I now encounter a different error:

“RuntimeError: CUDA error: an illegal memory access was encountered.”

This appears to be related to using int32 as the address dtype.

For reference, my query, key, and value shapes are [1600, 16, 729, 72]. When I reduce the batch size to 16, everything works correctly. Could you please clarify whether FA4 supports int64 addressing?

**Comment by jamesben6688** [comment]
This error has been fixed in the latest master commit.
