### ISSUE TITLE
Support for Blackwell Architecture

### ISSUE THREAD

**Issue by jiminbae** [Dao-AILab/flash-attention#2220]
Hi, I am trying to run `Isaac-GR00T` inference on an **NVIDIA AGX Thor** devkit.
However, I encountered a `RuntimeError: cudaErrorNoKernelImageForDevice`, and I suspect this is due to Flash Attention not supporting the Blackwell architecture (Thor) yet.

Code:

```
observation = {
    "video": {k: np.stack(step_data.images[k])[None] for k in step_data.images},  # stach images and add batch dimension
    "state": {k: step_data.states[k][None] for k in step_data.states},  # add batch dimension
    "action": {k: step_data.actions[k][None] for k in step_data.actions},  # add batch dimension
    "language": {
        modality_config["language"].modality_keys[0]: [[step_data.text]],  # add time and batch dimension
    }
}
predicted_action, info = policy.get_action(observation)
for key, value in predicted_action.items():
    print(key, value.shape)
```

Output:
```
Search for `cudaErrorNoKernelImageForDevice' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Environment:
OS: Ubuntu 24.04.3 LTS (Noble)
Kernel: 6.8.12-tegra
Architecture: aarch64 (ARM64)
GPU: NVIDIA Thor
NVIDIA Driver: 580.00
CUDA Version: 13.0 (nvcc 13.1.115)
PyTorch: 2.10.0+cu130
Flash Attention: 2.8.3
Python: 3.10.19

Does the current version of Flash Attention (2.8.3) officially support the AGX Thor (Blackwell) architecture?

If not, is there an estimated timeline for support, or any recommended workaround (e.g., specific build flags for building from source)?

Thanks in advance!

**Comment by Irfanuet191** [comment]
I am having the same problem have you solved the issue? I have tried Isaac Groot the setup you share for DGX even that didn't worked.
Thank You

**Comment by jiminbae** [comment]
@Irfanuet191 No, I couldn't solve this issue. Maybe we could use scaled_dot_product_attention() on PyTorch instead of flash attention?

Please let me know if you have any ideas or progress. Thanks!

**Comment by wookyungE** [comment]
I'm also using SDPA for inference since Flash Attention isn't supported on Blackwell yet. Some open-source models don't have a flag for SDPA, but I was able to run inference immediately after modifying that part in the modeling file.

To clarify, my focus is on MLLM inference rather than robotics, so I can't say for certain about the robotics side of things.

**Comment by Irfanuet191** [comment]
@jiminbae I finally resolved the Issue, you need to build FlashAttention from source, the prebuilt FlashAttention wheels do not include support for the Blackwell architecture:

Clone this repo and build using:
"python setup.py install"

Note that the build process can take significantly longer on Thor, so please be patient.

Make sure you are using CUDA 13.0, PyTorch 2.10, and the uv-based environment provided by Groot. 

It’s also recommended to allocate all available resources to the build process. Avoid running any additional processes in the background to ensure a smooth and faster compilation

Thank you!

**Comment by jiminbae** [comment]
@Irfanuet191 I didn't completely understand, did you install Torch and all other packages on uv environment?

**Comment by Irfanuet191** [comment]
Yes separately installed the latest torch and all other packages in uv environment.

**Comment by jiminbae** [comment]
@Irfanuet191 sorry for the many questions, how did you get torch 13.0 for aarch64?

**Comment by Irfanuet191** [comment]
Just use normal torch installation

uv pip install torch torchvision --index-url https://download.pytorch.org/whl/cu130
