### ISSUE TITLE
CUDA error: an illegal memory access was encountered during backward

### ISSUE THREAD

**Issue by carmocca** [Dao-AILab/flash-attention#338]
Following up on https://github.com/Dao-AILab/flash-attention/issues/325

The problem seems to be caused by the changing sequence length of each sample

```python
    loss.backward()
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/_tensor.py", line 482, in backward
    return handle_torch_function(
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/overrides.py", line 1542, in handle_torch_function
    result = mode.__torch_function__(public_api, types, args, kwargs)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/utils/_device.py", line 76, in __torch_function__
    return func(*args, **kwargs)
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/_tensor.py", line 491, in backward
    torch.autograd.backward(
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/carlos/venv/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/carlos/venv/lib/python3.10/site-packages/flash_attn-2.0.0.post1-py3.10-linux-x86_64.egg/flash_attn/flash_attn_interface.py", line 267, in backward
    _flash_attn_backward(
  File "/home/carlos/venv/lib/python3.10/site-packages/flash_attn-2.0.0.post1-py3.10-linux-x86_64.egg/flash_attn/flash_attn_interface.py", line 66, in _flash_attn_backward
    dq, dk, dv, softmax_d, = flash_attn_cuda.bwd(
RuntimeError: CUDA error: an illegal memory access was encountered

```

## Reproduction steps

```bash
git clone https://github.com/Lightning-AI/lit-gpt
cd lit-gpt

touch repro.py
# add snippet below to repro.py

CUDA_LAUNCH_BLOCKING=1 python repro.py
```

The [lit-gpt model](https://github.com/Lightning-AI/lit-gpt/blob/main/lit_gpt/model.py) is a simple PyTorch implementation of your typical LLM. For this reproduction I've set the `pythia-70m` configuration.

The contents of `repro.py` are:

```python
import random
import torch


from lit_gpt.model import GPT


def main():
    torch.set_default_device(torch.device("cuda"))
    torch.set_default_dtype(torch.bfloat16)

    model = GPT.from_name("pythia-70m")

    for iter in range(999):
        t = random.randint(0, 1028)
        input_ids = torch.randint(0, 10, (1, t), dtype=torch.long)
        print(input_ids.shape)

        logits = model(input_ids)
        loss = logits.sum()
        loss.backward()


if __name__ == "__main__":
    main()
```

It might fail sooner or later, but it seems to always fail on my setup.

# Environment

I installed current Flash attention master, other than that it's the same as in https://github.com/Dao-AILab/flash-attention/issues/325

**Comment by carmocca** [comment]
> The problem seems to be caused by the changing sequence length of each sample

This isn't true. I tried some other scripts with a fixed sequence length and got the same error. Unless it's an issue with my specific setup it means that no finetuning or pretraining script in lit-gpt can use this at the moment.

**Comment by tridao** [comment]
Thanks for the bug report, this is very valuable to us! I've trained many GPT-style models with FlashAttention-2 but this is a complete rewrite so there might be edge cases.

Do you have the shape of the inputs to the attention function (batch, seqlen, nheads, headdim) and dtype (fp16/bf16), causal or not, type of GPU. That would help me reproduce and debug.

**Comment by carmocca** [comment]
Here you go

Using `causal=True` and `dropout_p=0.0`:

```python
query torch.Size([1, 238, 8, 64]) cuda:0 torch.bfloat16
key torch.Size([1, 238, 8, 64]) cuda:0 torch.bfloat16
value torch.Size([1, 238, 8, 64]) cuda:0 torch.bfloat16
```

<details>
<summary>Environment</summary>

```python
Collecting environment information...
PyTorch version: 2.1.0.dev20230620+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-75-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 525.105.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   43 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          256
On-line CPU(s) list:             0-254
Off-line CPU(s) list:            255
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7742 64-Core Processor
CPU family:                      23
Model:                           49
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       2
Stepping:                        0
Frequency boost:                 enabled
CPU max MHz:                     2250.0000
CPU min MHz:                     0.0000
BogoMIPS:                        4499.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es
Virtualization:                  AMD-V
L1d cache:                       4 MiB (128 instances)
L1i cache:                       4 MiB (128 instances)
L2 cache:                        64 MiB (128 instances)
L3 cache:                        512 MiB (32 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-63,128-191
NUMA node1 CPU(s):               64-127,192-254
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] lovely-numpy==0.2.9
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.0
[pip3] pytorch-lightning==2.0.3
[pip3] pytorch-triton==2.1.0+440fd1bf20
[pip3] torch==2.1.0.dev20230620+cu121
[pip3] torchmetrics==0.11.4
[conda] Could not collect
```

</details>

**Comment by ShomyLiu** [comment]
The same issues here. 
 illegal memory access when backwards.

**Comment by tridao** [comment]
I just pushed a commit to hopefully fix this. @carmocca @ShomyLiu can you try it? If it works I'll cut a release.

**Comment by ShomyLiu** [comment]
Thanks for your effort, I will try right now @tridao

**Comment by ShomyLiu** [comment]
@tridao  Hi, there is a error when compiling from source, could you help have a look?
the log:
```
building 'flash_attn_2_cuda' extension
creating build/temp.linux-x86_64-3.10
creating build/temp.linux-x86_64-3.10/csrc
creating build/temp.linux-x86_64-3.10/csrc/flash_attn
creating build/temp.linux-x86_64-3.10/csrc/flash_attn/src
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/disk1/liuhongtao01/flash-attention-main/csrc/flash_attn -I/home/disk1/liuhongtao01/flash-attention-main/csrc/flash_attn/src -I/home/disk1/liuhongtao01/flash-attention-main/csrc/cutlass/include -I/usr/local/lib/python3.10/dist-packages/torch/include -I/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.10/dist-packages/torch/include/TH -I/usr/local/lib/python3.10/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.10 -c csrc/flash_attn/flash_api.cpp -o build/temp.linux-x86_64-3.10/csrc/flash_attn/flash_api.o -O3 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1016" -DTORCH_EXTENSION_NAME=flash_attn_2_cuda -D_GLIBCXX_USE_CXX11_ABI=1
csrc/flash_attn/flash_api.cpp: In function ‘void set_params_fprop(Flash_fwd_params&, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, at::Tensor, at::Tensor, at::Tensor, at::Tensor, void*, void*, void*, void*, float, float, bool)’:
csrc/flash_attn/flash_api.cpp:42:11: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct Flash_fwd_params’; use assignment or value-initialization instead [-Wclass-memaccess]
   42 |     memset(&params, 0, sizeof(params));
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from csrc/flash_attn/flash_api.cpp:11:
/home/disk1/liuhongtao01/flash-attention-main/csrc/flash_attn/src/flash.h:52:8: note: ‘struct Flash_fwd_params’ declared here
   52 | struct Flash_fwd_params : public Qkv_params {
      |        ^~~~~~~~~~~~~~~~
/usr/local/cuda/bin/nvcc -I/home/disk1/liuhongtao01/flash-attention-main/csrc/flash_attn -I/home/disk1/liuhongtao01/flash-attention-main/csrc/flash_attn/src -I/home/disk1/liuhongtao01/flash-attention-main/csrc/cutlass/include -I/usr/local/lib/python3.10/dist-packages/torch/include -I/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.10/dist-packages/torch/include/TH -I/usr/local/lib/python3.10/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.10 -c csrc/flash_attn/src/flash_bwd_hdim128_bf16_sm80.cu -o build/temp.linux-x86_64-3.10/csrc/flash_attn/src/flash_bwd_hdim128_bf16_sm80.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1016" -DTORCH_EXTENSION_NAME=flash_attn_2_cuda -D_GLIBCXX_USE_CXX11_ABI=1
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
nvcc: Aborted
error: command '/usr/local/cuda/bin/nvcc' failed with exit code 255
```
The env used in ngc-2306:
```
cuda: 12.1
torch: 2.1.0a0+4136153
```
Thanks

**Comment by ShomyLiu** [comment]
Hi，when I try to install from source, there is a error in compile:
```
running build_ext
building 'flash_attn_2_cuda' extension
creating build/temp.linux-x86_64-3.10
creating build/temp.linux-x86_64-3.10/csrc
creating build/temp.linux-x86_64-3.10/csrc/flash_attn
creating build/temp.linux-x86_64-3.10/csrc/flash_attn/src
x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/disk1//flash-attention-main/csrc/flash_attn -I/home/disk1//flash-attention-main/csrc/flash_attn/src -I/home/disk1//flash-attention-main/csrc/cutlass/include -I/usr/local/lib/python3.10/dist-packages/torch/include -I/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.10/dist-packages/torch/include/TH -I/usr/local/lib/python3.10/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.10 -c csrc/flash_attn/flash_api.cpp -o build/temp.linux-x86_64-3.10/csrc/flash_attn/flash_api.o -O3 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1016" -DTORCH_EXTENSION_NAME=flash_attn_2_cuda -D_GLIBCXX_USE_CXX11_ABI=1
csrc/flash_attn/flash_api.cpp: In function ‘void set_params_fprop(Flash_fwd_params&, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, at::Tensor, at::Tensor, at::Tensor, at::Tensor, void*, void*, void*, void*, float, float, bool)’:
csrc/flash_attn/flash_api.cpp:42:11: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct Flash_fwd_params’; use assignment or value-initialization instead [-Wclass-memaccess]
   42 |     memset(&params, 0, sizeof(params));
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from csrc/flash_attn/flash_api.cpp:11:
/home/disk1//flash-attention-main/csrc/flash_attn/src/flash.h:52:8: note: ‘struct Flash_fwd_params’ declared here
   52 | struct Flash_fwd_params : public Qkv_params {
      |        ^~~~~~~~~~~~~~~~
/usr/local/cuda/bin/nvcc -I/home/disk1/flash-attention-main/csrc/flash_attn -I/home/disk1/flash-attention-main/csrc/flash_attn/src -I/home/disk1/flash-attention-main/csrc/cutlass/include -I/usr/local/lib/python3.10/dist-packages/torch/include -I/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.10/dist-packages/torch/include/TH -I/usr/local/lib/python3.10/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.10 -c csrc/flash_attn/src/flash_bwd_hdim128_bf16_sm80.cu -o build/temp.linux-x86_64-3.10/csrc/flash_attn/src/flash_bwd_hdim128_bf16_sm80.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1016" -DTORCH_EXTENSION_NAME=flash_attn_2_cuda -D_GLIBCXX_USE_CXX11_ABI=1
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
nvcc: Aborted
error: command '/usr/local/cuda/bin/nvcc' failed with exit code 255
```
My env is based on ngc-2306:
```
torch: 2.1.0
cuda: 12.1
```

**Comment by griff4692** [comment]
I can confirm that reinstalling from source works for me -- I had the same error as @carmocca until I installed from source.  Thanks @tridao !!

**Comment by ShomyLiu** [comment]
@tridao  Yes, I can also confirm that the new commit could solve this problem. Thanks again!

**Comment by carmocca** [comment]
It worked! :1st_place_medal:

**Comment by seungduk-yanolja** [comment]
```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/axo/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/miniconda3/envs/axo/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/apps/axolotl/src/axolotl/cli/train.py", line 59, in <module>
    fire.Fire(do_cli)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/apps/axolotl/src/axolotl/cli/train.py", line 35, in do_cli
    return do_train(parsed_cfg, parsed_cli_args)
  File "/home/user/apps/axolotl/src/axolotl/cli/train.py", line 55, in do_train
    return train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
  File "/home/user/apps/axolotl/src/axolotl/train.py", line 167, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/transformers/trainer.py", line 1561, in train
    return inner_training_loop(
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/transformers/trainer.py", line 1893, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/transformers/trainer.py", line 2822, in training_step
    self.accelerator.backward(loss)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/accelerate/accelerator.py", line 1964, in backward
    loss.backward(**kwargs)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 288, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 318, in backward
    _flash_attn_varlen_backward(
  File "/home/user/miniconda3/envs/axo/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 179, in _flash_attn_varlen_backward
    dq, dk, dv, softmax_d, = flash_attn_cuda.varlen_bwd(
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
I am experiencing the same issue. It happens exactly on the same step for the same dataset.
