### ISSUE TITLE
tests/test_flash_attn.py：fails conformance test----RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by YUANMU227** [Dao-AILab/flash-attention#454]
I used this command to test the performance of flash_attn2.  

I followed the operation from here: https://github.com/Dao-AILab/flash-attention#tests

`pytest -q -s -x tests/test_flash_attn.py `

Here, -x means it will stop when a faliure occurs.

here is the the output from termanal:

`Output max diff: 0.00048828125
Output mean diff: 2.1457672119140625e-05
Pytorch max diff: 0.00146484375
Pytorch mean diff: 5.9723854064941406e-05
dQ max diff: 0.0009765625
dK max diff: 0.0009765625
dV max diff: 0.0009765625
dQKV mean diff: 2.5272369384765625e-05
dQ Pytorch max diff: 0.001953125
dK Pytorch max diff: 0.001953125
dV Pytorch max diff: 0.001953125
dQKV Pytorch mean diff: 6.586313247680664e-05
.Output max diff: 0.00390625
Output mean diff: 0.00017261505126953125
Pytorch max diff: 0.01171875
Pytorch mean diff: 0.0004787445068359375
dQ max diff: 0.0078125
dK max diff: 0.0078125
dV max diff: 0.0078125
dQKV mean diff: 0.000202178955078125
dQ Pytorch max diff: 0.015625
dK Pytorch max diff: 0.015625
dV Pytorch max diff: 0.01953125
dQKV Pytorch mean diff: 0.000530242919921875
...
.Output max diff: 0.00048828125
Output mean diff: 2.0444393157958984e-05
Pytorch max diff: 0.001953125
Pytorch mean diff: 5.9485435485839844e-05
F
=================================================================== FAILURES ====================================================================
______________________________________________ test_flash_attn_qkvpacked[0.0-97-111-False-dtype0] _______________________________________________

seqlen = 97, d = 111, dropout_p = 0.0, causal = False, dtype = torch.float16

    @pytest.mark.parametrize('dtype', ([torch.float16] if is_sm75 else [torch.float16, torch.bfloat16]))
    # @pytest.mark.parametrize('dtype', [torch.float16])
    @pytest.mark.parametrize('causal', [False, True])
    # @pytest.mark.parametrize('causal', [True])
    @pytest.mark.parametrize('d', [32, 40, 59, 64, 80, 96, 111, 128, 160, 192, 224, 256])
    # @pytest.mark.parametrize('d', [32, 64, 96, 128, 160, 192, 224, 256])
    # @pytest.mark.parametrize('d', [32, 64, 96, 128])
    # @pytest.mark.parametrize('d', [64])
    # @pytest.mark.parametrize('seqlen', [128, 256, 384, 512, 768, 1024, 2048])
    @pytest.mark.parametrize('seqlen', [97, 128, 200, 256, 257, 384, 512, 768, 1024, 1025, 2048])
    # @pytest.mark.parametrize('seqlen', [97])
    @pytest.mark.parametrize('dropout_p', [0.0, 0.17])
    # @pytest.mark.parametrize('dropout_p', [0.17])
    def test_flash_attn_qkvpacked(seqlen, d, dropout_p, causal, dtype):
        if seqlen >= 2048 and torch.cuda.get_device_properties('cuda').total_memory <= 16 * 2**30:
            pytest.skip()  # Reference implementation OOM
        device = 'cuda'
        # set seed
        torch.random.manual_seed(0)
        batch_size = 16
        nheads = 9
        qkv = torch.randn(batch_size, seqlen, 3, nheads, d, device=device, dtype=dtype,
                          requires_grad=True)
        out, lse, S_dmask = flash_attn_qkvpacked_func(
            qkv, dropout_p, return_attn_probs=True, causal=causal
        )
        if dropout_p > 0.0:
            S_dmask_converted = convert_flash_attn_S_to_softmax(
                S_dmask, None, None, d, dropout_p > 0.0, causal=causal
            )[:, :, :seqlen, :seqlen]
            dropout_mask = S_dmask_converted >= 0
            attn_unnorm = S_dmask_converted.abs()
            attn = normalize_flash_attn_S(attn_unnorm, qkv[:, :, 0], qkv[:, :, 1], qkv[:, :, 2],
                                          None, None, dropout_p > 0.0, causal=causal)
            dropout_fraction = get_dropout_fraction(dropout_mask, None, None, causal=causal).item()
            print(f'Actual dropout fraction: {dropout_fraction}')
        else:
            dropout_mask = None
    
        out_ref, attn_ref = attention_qkvpacked_ref(qkv, None, dropout_p, dropout_mask, causal=causal)
        out_pt, attn_pt = attention_qkvpacked_ref(qkv, None, dropout_p, dropout_mask, causal=causal,
                                                  upcast=False, reorder_ops=True)
        # v = qkv[:, :, 2].float()
        # qk = torch.einsum('bshd,bthd->bhst', qkv[:, :, 0], qkv[:, :, 1]).float()
        # if causal:
        #     causal_mask = torch.triu(torch.ones(seqlen, seqlen, dtype=torch.bool, device=qkv.device), 1)
        #     qk.masked_fill_(causal_mask, float('-inf'))
        # m = qk.amax(-1, keepdim=True)
        # s_tmp = torch.exp((qk - m) / math.sqrt(d))
        # p_tmp = torch.softmax(qk / math.sqrt(d), -1)
        # p_dropped = p_tmp if dropout_mask is None else p_tmp.masked_fill(~dropout_mask, 0)
        # lse_ref = torch.logsumexp(qk / math.sqrt(d), -1)
        # qk_max1 = torch.max(qk[:, :, 128:, 192:], -1, keepdim=True).values
        # qk_max2 = torch.max(qk[:, :, 128:, 128:], -1, keepdim=True).values
        # qk_max3 = torch.max(qk[:, :, 128:, 64:], -1, keepdim=True).values
        # qk_max4 = torch.max(qk[:, :, 128:, :], -1, keepdim=True).values
        # o1 = torch.einsum('bhst,bthd->bshd', torch.exp((qk[:, :, 128:, 192:] - qk_max1) / math.sqrt(d)), v[:, 192:])
        # o2 = torch.einsum('bhst,bthd->bshd', torch.exp((qk[:, :, 128:, 128:] - qk_max2) / math.sqrt(d)), v[:, 128:])
        # o3 = torch.einsum('bhst,bthd->bshd', torch.exp((qk[:, :, 128:, 64:] - qk_max3) / math.sqrt(d)), v[:, 64:])
        # o4 = torch.einsum('bhst,bthd->bshd', torch.exp((qk[:, :, 128:, :] - qk_max4) / math.sqrt(d)), v[:, :])
        print(f'Output max diff: {(out - out_ref).abs().max().item()}')
        print(f'Output mean diff: {(out - out_ref).abs().mean().item()}')
        print(f'Pytorch max diff: {(out_pt - out_ref).abs().max().item()}')
        print(f'Pytorch mean diff: {(out_pt - out_ref).abs().mean().item()}')
        if dropout_p > 0.0:
            print(f'Attention max diff: {(attn - attn_ref).abs().max().item()}')
            print(f'Attention Pytorch max diff: {(attn_pt - attn_ref).abs().max().item()}')
    
        g = torch.randn_like(out)
        # do_o = (g.float() * out.float()).sum(-1)
        # dv_tmp = torch.einsum('bhts,bthd->bshd', attn_pt[:, :, :64], g[:, :64])
        # dv_tmp1 = torch.einsum('bhts,bthd->bshd', attn_pt[:, :, 64:], g[:, 64:])
        if d <= MAX_HEADDIM_SM8x or (is_sm80 or is_sm90):
            dqkv, = torch.autograd.grad(out, qkv, g)
            dqkv_ref, = torch.autograd.grad(out_ref, qkv, g)
            dqkv_pt, = torch.autograd.grad(out_pt, qkv, g)
    
            ############################################
>           print(f'dQ max diff: {(dqkv[:, :, 0] - dqkv_ref[:, :, 0]).abs().max().item()}')
E           RuntimeError: CUDA error: an illegal memory access was encountered
E           CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
E           For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
E           Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

tests/test_flash_attn.py:418: RuntimeError
============================================================ short test summary info ============================================================
FAILED tests/test_flash_attn.py::test_flash_attn_qkvpacked[0.0-97-111-False-dtype0] - RuntimeError: CUDA error: an illegal memory access was encountered
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
1 failed, 24 passed in 4.15s`

`E           RuntimeError: CUDA error: an illegal memory access was encountered
E           CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
E           For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
E           Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

I think the reason was OOM and there were too much test tries.

But how can I decrease the number of test tries?

**Comment by tridao** [comment]
Can you try commenting out some lines at the beginning of that test, e.g.:
```
#@pytest.mark.parametrize('dtype', ([torch.float16] if is_sm75 else [torch.float16, torch.bfloat16]))
@pytest.mark.parametrize('dtype', [torch.float16])
# @pytest.mark.parametrize('causal', [False, True])
@pytest.mark.parametrize('causal', [True])
# @pytest.mark.parametrize('d', [32, 40, 59, 64, 80, 96, 111, 128, 160, 192, 224, 256])
# @pytest.mark.parametrize('d', [32, 64, 96, 128, 160, 192, 224, 256])
@pytest.mark.parametrize('d', [32, 64, 96, 128])
# @pytest.mark.parametrize('d', [64])
# @pytest.mark.parametrize('seqlen', [128, 256, 384, 512, 768, 1024, 2048])
# @pytest.mark.parametrize('seqlen', [97, 128, 200, 256, 257, 384, 512, 768, 1024, 1025, 2048])
@pytest.mark.parametrize('seqlen', [97])
@pytest.mark.parametrize('dropout_p', [0.0, 0.17])
# @pytest.mark.parametrize('dropout_p', [0.17])
```

**Comment by YUANMU227** [comment]
@tridao hey, thanks for your reply. 

I solved this problem. It was because of too many test inputs and some of them were too large to leed to the OOM.

So I decreased the number of the inputs and avoid the problem.

However, there is another issue:

`============================================================= short test summary info =============================================================
FAILED tests/test_flash_attn.py::test_flash_attn_race_condition[0.0-128-128-False-dtype0] - assert False
FAILED tests/test_flash_attn.py::test_flash_attn_race_condition[0.0-128-128-True-dtype0] - assert False
FAILED tests/test_flash_attn.py::test_flash_attn_bwd_transpose[128-128-False-dtype0] - AssertionError: assert 236.75 <= (2 * 0.0009765625)
FAILED tests/test_flash_attn.py::test_flash_attn_bwd_transpose[128-128-False-dtype1] - AssertionError: assert 22144.0 <= (2 * 0.0078125)
FAILED tests/test_flash_attn.py::test_flash_attn_bwd_transpose[128-128-True-dtype0] - AssertionError: assert 2.724609375 <= (2 * 0.001953125)
FAILED tests/test_flash_attn.py::test_flash_attn_bwd_transpose[128-128-True-dtype1] - AssertionError: assert 95.5 <= (2 * 0.015625)
6 failed, 56 passed in 4.23s`

**Comment by YUANMU227** [comment]
`____________________________________________ test_flash_attn_race_condition[0.0-128-128-False-dtype0] _____________________________________________

seqlen = 128, d = 128, dropout_p = 0.0, causal = False, dtype = torch.float16

    @pytest.mark.parametrize('dtype', [torch.float16])
    @pytest.mark.parametrize('causal', [False, True])
    # @pytest.mark.parametrize('causal', [False])
    # @pytest.mark.parametrize('d', [32, 56, 64, 80, 96, 128])
    # @pytest.mark.parametrize('d', [32, 64, 96, 128, 160, 192])
    @pytest.mark.parametrize('d', [128])
    # @pytest.mark.parametrize('seqlen', [97, 128, 200, 256, 257, 384, 512, 768, 1024, 1025, 2048])
    # @pytest.mark.parametrize('seqlen', [128, 256, 384, 512, 768, 1024, 2048])
    @pytest.mark.parametrize('seqlen', [128])
    # @pytest.mark.parametrize('dropout_p', [0.0, 0.17])
    @pytest.mark.parametrize('dropout_p', [0.0])
    def test_flash_attn_race_condition(seqlen, d, dropout_p, causal, dtype):
        device = 'cuda'
        # set seed
        torch.random.manual_seed(0)
        batch_size = 60  # Sometimes we need large batch size for the race conditions to trigger
        nheads = 4
        qkv = torch.randn(batch_size, seqlen, 3, nheads, d, device=device, dtype=dtype,
                          requires_grad=True)
        out0, lse0, _ = flash_attn_qkvpacked_func(
            qkv, dropout_p, return_attn_probs=True, causal=causal
        )
        g = torch.randn_like(out0)
        if d <= MAX_HEADDIM_SM8x or (is_sm80 or is_sm90):
            dqkv0, = torch.autograd.grad(out0, qkv, g)
            # Numerical error if we just do any arithmetic on dq
            dq_atol = 2 * ((dqkv0[:, :, 0] + 0.3 - 0.3) - dqkv0[:, :, 0]).abs().max().item()
    
        for i in range(200):
            # torch.cuda.empty_cache()
            torch.random.manual_seed(0)
            out, lse, S_dmask = flash_attn_qkvpacked_func(
                qkv, dropout_p, return_attn_probs=True, causal=causal
            )
            assert torch.equal(out, out0)
            assert torch.equal(lse, lse0)
    
            if d <= MAX_HEADDIM_SM8x or (is_sm80 or is_sm90):
                dqkv, = torch.autograd.grad(out, qkv, g)
                dq_equal = torch.allclose(dqkv[:, :, 0], dqkv0[:, :, 0], atol=dq_atol)
                if not dq_equal:
                    dq0 = dqkv0[:, :, 0]
                    dq = dqkv[:, :, 0]
                    print(f'Iter {i}, {dq_atol = }, dQ max diff: {(dqkv[:, :, 0] - dqkv0[:, :, 0]).abs().max().item()}')
>               assert dq_equal
E               assert False

tests/test_flash_attn.py:840: AssertionError`

**Comment by tridao** [comment]
What's your GPU, CUDA version, and what's the version of flash-attn?

**Comment by YUANMU227** [comment]
@tridao GPU: NVIDIA GeForce RTX 3090. CUDA: 11.4. flash-attn: 2.0.6.
