### ISSUE TITLE
Flash Attention OOM on inference 

### ISSUE THREAD

**Issue by jmzeng** [Dao-AILab/flash-attention#590]
Hi, I'm getting a weird issue where FlashAttention2 OOMs on inference with the following:

```
File "/usr/lib/python3/dist-packages/medical_coding_research/modeling/llms/utils/llama2_flash_attn_patch.py", line 99, in forward
    x_unpad, indices, cu_q_lens, max_s = unpad_input(x, key_padding_mask)
  File "/usr/lib/python3/dist-packages/flash_attn/bert_padding.py", line 118, in unpad_input
    index_first_axis(rearrange(hidden_states, "b s ... -> (b s) ..."), indices),
  File "/usr/lib/python3/dist-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/lib/python3/dist-packages/flash_attn/bert_padding.py", line 17, in forward
    return torch.gather(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 744.00 MiB (GPU 2; 79.11 GiB total capacity; 76.18 GiB already allocated; 696.69 MiB free; 77.57 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I am running on H100 80GB GPUs and was able to train with a per device batch size of 2 with the same patch, so this is a little odd to me. 

For reference, the patch I'm using is here:
https://github.com/DachengLi1/LongChat/blob/longeval/longchat/train/monkey_patch/llama_flash_attn_monkey_patch.py

I tested on both versions of 2.1.0 and 2.3.0

**Comment by tridao** [comment]
Yeah hard for me to tell what's going on. To isolate, you can try not unpadding input at each layer to see if that's the cause of OOM.

**Comment by jmzeng** [comment]
I think the old monkey patch no longer works. I updated to the latest transformers version, 4.34.0 with `use_flash_attn2` and it now works. Thanks for the help!
