### ISSUE TITLE
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by JacksonCakes** [Dao-AILab/flash-attention#631]
Hi, I have installed flash-attention using:
```
pip install flash-attn --no-build-isolation
```
The installation works fine. But when I trying to import it using following scripts:
```
import torch
print(torch.version)
print(torch.__version__)
print(torch.version.cuda)
print(torch.backends.cudnn.version())
print(torch.cuda.is_available())
from flash_attn import flash_attn_qkvpacked_func, flash_attn_func
```
I received the following error:
```
<module 'torch.version' from '/home/jackson/.conda/envs/llms/lib/python3.10/site-packages/torch/version.py'>
2.1.0
11.8
8700
True
Traceback (most recent call last):
  File "/home/jackson/llm_tuner/test.py", line 7, in <module>
    from flash_attn import flash_attn_qkvpacked_func, flash_attn_func
  File "/home/jackson/.conda/envs/llms/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/home/jackson/.conda/envs/llms/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 8, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
```

Here is the nvcc version in case it's needed for debugging:
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**Comment by devenami** [comment]
I have same error

**Comment by tridao** [comment]
I think it's because your env doesn't have some of the CUDA development libraries. I don't know how to fix it exactly. You can also try the nvcr pytorch image.

**Comment by maxschmitt** [comment]
I was facing the same error. Compiling from source (as described in the README.md) resolved the problem for me.
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
```

```
...
torch               2.0.1+cu117
...
```

**Comment by Kk1984up** [comment]
me too, how to fix the error,

**Comment by devenami** [comment]
@Kk1984up you can use lower torch version

**Comment by tetratorus** [comment]
Fixed it by setting my LD_LIBRARY_PATH

**Comment by itmohitgoswami** [comment]
Hey! I am also getting same error.

**Comment by JacksonCakes** [comment]
Hey, for those encountering similar issues, I recommend checking your versions of torch/cuda and flash-attn. Below is the script I use to verify my torch/cuda versions and confirm if my flash-attn installation was successful:
```
import torch
print(torch.version)
print(torch.__version__)
print(torch.version.cuda)
print(torch.backends.cudnn.version())
print(torch.cuda.is_available())
from flash_attn import flash_attn_qkvpacked_func, flash_attn_func
```
following is my output:
```
2.1.0+cu121
12.1
8902
True
```
and my **flash-attn version == 2.3.4**

I've tested flash-attn version 2.3.1.post1 and found it compatible with CUDA 11.8. Therefore, experimenting with different versions of cuda and flash-attn might resolve your issue.
