### ISSUE TITLE
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by OrenLeung** [Dao-AILab/flash-attention#728]
if flash-attn was installed through `conda` or `pip` where `pip` is installed through `conda` then it results in the following error.
this error does not occur when `flash-attn` is installed through pip and is in the user local site packages

```python
import torch
import flash_attn_2_cuda as flash_attn_cuda
```

results in Error
```bash
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
```

even tho libcudart.so is clearly in the conda site packages
```bash
/home/ubuntu/miniconda3/envs/ENV_NAME/lib/python3.10/site-packages/nvidia/cuda_runtime/lib/libcudart.so.12
```

**Comment by zhy1206** [comment]
I meet the same problem. 
How did you fixed it?

**Comment by OrenLeung** [comment]
symlink all the nvidia shared libs from the conda path to yr cuda_home path at `/usr/local/cuda...`

**Comment by OrenLeung** [comment]
or just also download the nvidia libraries directly instead of through conda

**Comment by zhy1206** [comment]
Thank you. I finally solved the problem by lowering the cuda version from 12.1 to 11.8. 
Maybe my previous cuda version is wrong.

**Comment by OrenLeung** [comment]
> Thank you. I finally solved the problem by lowering the cuda version from 12.1 to 11.8. Maybe my previous cuda version is wrong.
@hummingbird2030 glad to hear 🥳
