### ISSUE TITLE
Illegal Memory Access when seq_len >= 256 * K and embed_dim / tp_size >= 6144

### ISSUE THREAD

**Issue by li126com** [Dao-AILab/flash-attention#767]
I met the illegal memory access error when testing multi head attention based on flash-atten.
Environment configuration is as follows:
`
flash_atten: 2.0.0 or 2.4.2
cuda: 11.7
torch: 1.13.1
python: 3.10.0
GPU: A800 * 1
`

**Comment by stas00** [comment]
As I have run into a similar issue with `tensor.numel()>2^31`, I was told to use FA3 and it solved the problem. And the other thing I was told is that FA2 will not be fixed since FA3 is going to replace FA2.

The only issue at the moment is that FA3 doesn't work on Blackwell, but supposedly should be working there soonish.
